import random
import pandas as pd
import numpy as np
import unittest

def task_func(n,
          domain="samplewebsite.com",
          categories=['Sports', 'Technology', 'Health', 'Science', 'Business'],
          random_seed=None):
    """
    Generate 'n' random articles with titles, URLs, IDs, categories, and views, and return them as a DataFrame.
    Views are generated by sampling from a poisson distribution with lambda=1000.
    
    Parameters:
    n (int): The number of articles to generate.
    domain (str): The domain name for article URLs. Default is "samplewebsite.com".
    categories (list): List of categories for the articles. Default values are ['Sports', 'Technology', 'Health', 'Science', 'Business'].
    random_seed(int): Seed for rng. Used for generating views and choosing categories.

    Returns:
    DataFrame: A pandas DataFrame with columns: 'title', 'title_url', 'id', 'category', 'views'.
    """
    random.seed(random_seed)
    np.random.seed(random_seed)

    data = []
    for _ in range(n):
        title = f"Article {_}"
        title_url = f"{domain}/Article_{_}"
        id = _
        category = random.choice(categories)
        views = np.random.poisson(1000)
        data.append({'title': title, 'title_url': title_url, 'id': id, 'category': category, 'views': views})

    df = pd.DataFrame(data)
    return df

class TestTaskFunc(unittest.TestCase):

    def test_output_dataframe_shape(self):
        """Test if the output DataFrame has the correct shape."""
        df = task_func(10)
        self.assertEqual(df.shape, (10, 5))

    def test_output_dataframe_columns(self):
        """Test if the output DataFrame has the correct columns."""
        df = task_func(5)
        expected_columns = ['title', 'title_url', 'id', 'category', 'views']
        self.assertListEqual(list(df.columns), expected_columns)

    def test_article_ids_are_sequential(self):
        """Test if the article IDs are sequential starting from 0."""
        df = task_func(10)
        self.assertTrue(all(df['id'] == df.index))

    def test_views_are_positive(self):
        """Test if the views column has only positive values."""
        df = task_func(10)
        self.assertTrue((df['views'] >= 0).all())

    def test_category_selection_from_provided_list(self):
        """Test if the categories are selected from the provided list."""
        categories = ['A', 'B', 'C']
        df = task_func(10, categories=categories)
        self.assertTrue(all(df['category'].isin(categories)))

if __name__ == '__main__':
    unittest.main()